- name: Transfer the script
  copy:
    src: userscript.sh
    dest: /tmp/test_user.sh
    mode: 0777
  become: true

- name: Create a directory for the list of users
  file:
    path: /tmp/ansible
    state: directory
    mode: 0777
  become: true

- name: Execute the script
  command: ./test_user.sh
  args:
    chdir: /tmp/
  become: true

- name: Fetching the file on localhost
  shell: (cd /tmp/ansible/; find . -maxdepth 1 -type f) | cut -d '/' -f2
  register: files_to_copy

- fetch: 
    src: /tmp/ansible/{{item}} 
    dest: /ansible_disk/
  with_items: "{{ files_to_copy.stdout_lines}}"
